"""agrega tabla meals

Revision ID: 505c9a5f75e4
Revises: 4abfa186c2c2
Create Date: 2026-09-26 12:57:34.970382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505c9a5f75e4'
down_revision: Union[str, Sequence[str], None] = '4abfa186c2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_type', sa.String(length=30), nullable=False),
    sa.Column('meal_size', sa.SmallInteger(), nullable=False),
    sa.Column('meal_content', sa.String(length=500), nullable=True),
    sa.Column('drink', sa.String(length=60), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_id'), ['id'], unique=False)
        batch_op.create_index('ix_meals_user_recorded_on', ['user_id', 'recorded_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index('ix_meals_user_recorded_on')
        batch_op.drop_index(batch_op.f('ix_meals_id'))

    op.drop_table('meals')
    # ### end Alembic commands ###
