"""agrega tablas de ingresos

Revision ID: ac076711a735
Revises: 27dd878d152b
Siembra fuentes y subcategorias iniciales del usuario quemado (sin CRUD
todavia, mismo criterio que los tags en 31bdd71b624a_agrega_tablas_de_finanzas).
Los registros de prueba NO van aca: son datos, no esquema (ver
scripts/seed_income_samples.py).

Create Date: 2026-09-30 22:45:16.905798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# (name, type). type: DIRECT / INTEREST / ALL (aplica a ambos).
SOURCES_SEED = [
    ("Salario", "DIRECT"),
    ("Venta ocasional", "DIRECT"),
    ("Tyba", "INTEREST"),
    ("Cuenta de ahorros", "INTEREST"),
]
SUBCATEGORIES_SEED = [
    ("SALARIO BASE", "DIRECT"),
    ("EXTRA", "ALL"),
    ("RENDIMIENTOS", "INTEREST"),
]


# revision identifiers, used by Alembic.
revision: str = 'ac076711a735'
down_revision: Union[str, Sequence[str], None] = '27dd878d152b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fn_user_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fn_user_sources_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fn_user_sources')),
    sa.UniqueConstraint('user_id', 'name', name='uq_fn_user_sources_user_id_name')
    )
    op.create_table('fn_user_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fn_user_subcategories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fn_user_subcategories')),
    sa.UniqueConstraint('user_id', 'name', name='uq_fn_user_subcategories_user_id_name')
    )
    op.create_table('fn_user_direct_incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['fn_user_sources.id'], name=op.f('fk_fn_user_direct_incomes_source_id_fn_user_sources')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['fn_user_subcategories.id'], name=op.f('fk_fn_user_direct_incomes_subcategory_id_fn_user_subcategories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fn_user_direct_incomes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fn_user_direct_incomes'))
    )
    with op.batch_alter_table('fn_user_direct_incomes', schema=None) as batch_op:
        batch_op.create_index('ix_fn_user_direct_incomes_user_recorded_on', ['user_id', 'recorded_on'], unique=False)

    op.create_table('fn_user_interest_incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('start_of_month_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('end_of_month_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('deposits_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('withdrawals_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['fn_user_sources.id'], name=op.f('fk_fn_user_interest_incomes_source_id_fn_user_sources')),
    sa.ForeignKeyConstraint(['subcategory_id'], ['fn_user_subcategories.id'], name='fk_fn_user_interest_incomes_subcategory_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fn_user_interest_incomes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fn_user_interest_incomes')),
    sa.UniqueConstraint('user_id', 'source_id', 'recorded_on', name='uq_fn_user_interest_incomes_user_id_source_id_recorded_on')
    )
    with op.batch_alter_table('fn_user_interest_incomes', schema=None) as batch_op:
        batch_op.create_index('ix_fn_user_interest_incomes_user_recorded_on', ['user_id', 'recorded_on'], unique=False)

    op.create_table('fn_direct_incomes_tags',
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['fn_user_direct_incomes.id'], name=op.f('fk_fn_direct_incomes_tags_income_id_fn_user_direct_incomes')),
    sa.ForeignKeyConstraint(['tag_id'], ['fn_user_tags.id'], name=op.f('fk_fn_direct_incomes_tags_tag_id_fn_user_tags')),
    sa.PrimaryKeyConstraint('income_id', 'tag_id', name=op.f('pk_fn_direct_incomes_tags'))
    )
    op.create_table('fn_interest_incomes_tags',
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['fn_user_interest_incomes.id'], name=op.f('fk_fn_interest_incomes_tags_income_id_fn_user_interest_incomes')),
    sa.ForeignKeyConstraint(['tag_id'], ['fn_user_tags.id'], name=op.f('fk_fn_interest_incomes_tags_tag_id_fn_user_tags')),
    sa.PrimaryKeyConstraint('income_id', 'tag_id', name=op.f('pk_fn_interest_incomes_tags'))
    )
    # ### end Alembic commands ###

    # En una base nueva el usuario 1 aun no existe (lo crea la app al
    # arrancar): sin este chequeo el INSERT violaria la FK.
    if op.get_bind().execute(sa.text('SELECT 1 FROM users WHERE id = 1')).scalar():
        now = sa.func.now()
        for table_name, seed in (
            ('fn_user_sources', SOURCES_SEED),
            ('fn_user_subcategories', SUBCATEGORIES_SEED),
        ):
            table = sa.table(
                table_name,
                sa.column('user_id', sa.Integer),
                sa.column('type', sa.String),
                sa.column('name', sa.String),
                sa.column('created_at', sa.DateTime(timezone=True)),
            )
            op.execute(
                table.insert().values(
                    [
                        {'user_id': 1, 'type': type_, 'name': name, 'created_at': now}
                        for name, type_ in seed
                    ]
                )
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fn_interest_incomes_tags')
    op.drop_table('fn_direct_incomes_tags')
    with op.batch_alter_table('fn_user_interest_incomes', schema=None) as batch_op:
        batch_op.drop_index('ix_fn_user_interest_incomes_user_recorded_on')

    op.drop_table('fn_user_interest_incomes')
    with op.batch_alter_table('fn_user_direct_incomes', schema=None) as batch_op:
        batch_op.drop_index('ix_fn_user_direct_incomes_user_recorded_on')

    op.drop_table('fn_user_direct_incomes')
    op.drop_table('fn_user_subcategories')
    op.drop_table('fn_user_sources')
    # ### end Alembic commands ###
