"""linea base del esquema actual

Revision ID: cf2ce11c7a8b
Revises: 
Create Date: 2026-09-23 21:37:09.877731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2ce11c7a8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cld_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('first_day', sa.Date(), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cld_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cld_events_id'), ['id'], unique=False)

    op.create_table('dummy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dummy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dummy_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='America/Bogota', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('cl_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ENABLED', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cl_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cl_categories_id'), ['id'], unique=False)
        batch_op.create_index('ix_cl_categories_user_priority', ['user_id', 'priority'], unique=False)

    op.create_table('cl_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_day', sa.Date(), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cl_week', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cl_week_id'), ['id'], unique=False)

    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weights_id'), ['id'], unique=False)
        batch_op.create_index('ix_weights_user_recorded_on', ['user_id', 'recorded_on'], unique=False)

    op.create_table('cl_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cl_week_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('day_of_week', sa.String(length=2), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cl_categories.id'], ),
    sa.ForeignKeyConstraint(['cl_week_id'], ['cl_week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cl_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cl_tasks_id'), ['id'], unique=False)

    op.create_table('cl_template_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['cl_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cl_template_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cl_template_tasks_id'), ['id'], unique=False)

    op.create_table('cl_week_category_day_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cl_week_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('points_possible', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cl_categories.id'], ),
    sa.ForeignKeyConstraint(['cl_week_id'], ['cl_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cl_week_id', 'category_id', 'day_of_week', name='uq_wcds_week_category_day')
    )
    with op.batch_alter_table('cl_week_category_day_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cl_week_category_day_score_id'), ['id'], unique=False)
        batch_op.create_index('ix_wcds_category', ['category_id'], unique=False)
        batch_op.create_index('ix_wcds_week', ['cl_week_id'], unique=False)

    op.create_table('cld_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('repeat_mode', sa.String(length=10), nullable=True),
    sa.Column('repeat_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('add_to_checklist', sa.Boolean(), nullable=False),
    sa.Column('excluded_dates', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cl_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cld_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cld_tasks_id'), ['id'], unique=False)

    op.create_table('cld_user_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('first_day', sa.Date(), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['cl_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cld_user_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cld_user_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cld_user_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cld_user_events_id'))

    op.drop_table('cld_user_events')
    with op.batch_alter_table('cld_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cld_tasks_id'))

    op.drop_table('cld_tasks')
    with op.batch_alter_table('cl_week_category_day_score', schema=None) as batch_op:
        batch_op.drop_index('ix_wcds_week')
        batch_op.drop_index('ix_wcds_category')
        batch_op.drop_index(batch_op.f('ix_cl_week_category_day_score_id'))

    op.drop_table('cl_week_category_day_score')
    with op.batch_alter_table('cl_template_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cl_template_tasks_id'))

    op.drop_table('cl_template_tasks')
    with op.batch_alter_table('cl_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cl_tasks_id'))

    op.drop_table('cl_tasks')
    with op.batch_alter_table('weights', schema=None) as batch_op:
        batch_op.drop_index('ix_weights_user_recorded_on')
        batch_op.drop_index(batch_op.f('ix_weights_id'))

    op.drop_table('weights')
    with op.batch_alter_table('cl_week', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cl_week_id'))

    op.drop_table('cl_week')
    with op.batch_alter_table('cl_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_cl_categories_user_priority')
        batch_op.drop_index(batch_op.f('ix_cl_categories_id'))

    op.drop_table('cl_categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('dummy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dummy_id'))

    op.drop_table('dummy')
    with op.batch_alter_table('cld_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cld_events_id'))

    op.drop_table('cld_events')
    # ### end Alembic commands ###
