"""unicidad de intereses por subcategoria

Revision ID: ebddf5bc354d
Revises: a3c58e1f9b72
Create Date: 2026-10-04 18:55:09.614455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebddf5bc354d'
down_revision: Union[str, Sequence[str], None] = 'a3c58e1f9b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fn_user_interest_incomes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_fn_user_interest_incomes_user_id_source_id_recorded_on'), type_='unique')
        batch_op.create_unique_constraint('uq_fn_user_interest_incomes_subcategory_period', ['user_id', 'source_id', 'subcategory_id', 'recorded_on'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fn_user_interest_incomes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fn_user_interest_incomes_subcategory_period', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_fn_user_interest_incomes_user_id_source_id_recorded_on'), ['user_id', 'source_id', 'recorded_on'])

    # ### end Alembic commands ###
