"""Interfaz (Protocol) del acceso a datos de categorias de checklist."""

from typing import Protocol, Sequence

from app.db.models.checklist import ChecklistCategory


class CategoryRepository(Protocol):
    def list_by_user(self, user_id: int) -> Sequence[ChecklistCategory]: ...

    def get(self, category_id: int) -> ChecklistCategory | None: ...

    def add(self, category: ChecklistCategory) -> None: ...

    def delete(self, category: ChecklistCategory) -> None: ...

    def has_template_tasks(self, category_id: int) -> bool: ...

    def commit(self) -> None: ...

    def refresh(self, category: ChecklistCategory) -> None: ...
